### ISSUE TITLE
Question about partition server ?

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#35] opened 2019-11-01 08:54 UTC
I have 2 question when deploy system . I deploy system vearch  into 2 partition server with 30 million items and I have many issues:
  1. On 2 partition server ,server A  appear file dump.done  , another server B appear file **dumping.done** . So when I reload partition server B , I received error: 
ERROR 2019-11-01 15:16:56,806 gamma_engine.cc:736 dump.done cannot be found in [GO_PATH/data_vearch/data/data/29/2019-10-27-23:04:35]

  2. When I excute search command through the system ,  It took about ~1000ms for per request 
with config default : ivfpq parameters: **metric_type=1, nprobe=10, ncentroids=256, nsubvector=32, nbits_per_idx=8 . and my vector dimension = 512**  . I think it slowly because I chop up the vectors 512  into 32  sub-vectors. Can you recommend a suitable configuration for this amount of data ? 
Log query from router : [ps_space_service.go:410] [DEBUG] Max search partitionID:[30] use time:[1118]

**Comment by qiutianme** [comment] 2019-11-01 09:17
Which version of your code is it？We release v0.2 in recently days

**Comment by phamthanhtri** [comment] 2019-11-01 09:20
@qiutianme , I used version v0.1  download from Oct-24

**Comment by qiutianme** [comment] 2019-11-01 09:40
@phamthanhtri For Question 2, how many cpu cores you host/server has?

**Comment by phamthanhtri** [comment] 2019-11-01 09:47
@qiutianme  
Server with partitionID = 29  has 24cores , 128GB Ram.
Server with partitionID = 30  has 40cores , 128GB Ram. Current when loaded data in memory , it used 33.8GB for 13.8 million items.

**Comment by qiutianme** [comment] 2019-11-01 10:16
please check if your cpu cores are fully occupied  by vearch, we thought it may be the problem of openmp library

**Comment by phamthanhtri** [comment] 2019-11-01 10:30
@qiutianme 
Exactly .  I test run 100 request search, vearch are fully occupied CPU cores .

**Comment by qiutianme** [comment] 2019-11-01 10:46
what's the value of topn ?

**Comment by phamthanhtri** [comment] 2019-11-01 10:53
I used topN =10 for request search

**Comment by qiutianme** [comment] 2019-11-01 11:17
if your vectors are the same one？

**Comment by phamthanhtri** [comment] 2019-11-01 11:45
I don't understand . My vector has 512 dimension in database and search

**Comment by qiutianme** [comment] 2019-11-01 12:03
Yes, but we wonder if your vectors are equal to each other. eg 30 millions vector are [0.1, 0.2, 0.3 .......] which is 512 dimensions

**Comment by qiutianme** [comment] 2019-11-04 02:14
@phamthanhtri Please show us the table(space) schema, thanks!

**Comment by ljeagle** [comment] 2019-11-04 02:16
@phamthanhtri, Hi, Could you please give the schema of creating table?

**Comment by phamthanhtri** [comment] 2019-11-04 02:26
My schema :
{"db": True,
            "method": 1,
            "columns": {
                "imageurl": {
                    "type": "keyword"
                },
                "boundingbox": {
                    "type": "keyword"
                },
                "label": {
                    "type": "keyword"
                },
                "uid": {
                    "type": "keyword"
                }
            },
            "feature": {
                "type": "vector",
                "filed": "imageurl",
                "model_id": "vgg16",
                "dimension": 512
            }
            }

I used feature build from my model before.

**Comment by qiutianme** [comment] 2019-11-04 03:07
we found the problem is that you didn't set index_size when create the space, so the PQ index is not build. Please set it just like following

{
"engine": {"name": "gamma", "metric_type": method,"max_size":32000000, "index_size": 100000},
}

It's also our mistake, we didn't set "index_size" parameter in api doc, we will update it later.

**Comment by qiutianme** [comment] 2019-11-04 03:17
@phamthanhtri And If you don't want to recreate space, you can force build PQ index by using api http://$master_ip:$master_port/db_name/space_name/_forcemerge

**Comment by qiutianme** [comment] 2019-11-04 03:29
@phamthanhtri Sorry! The api is http://$router_ip:$router_port/db_name/space_name/_forcemerge

**Comment by phamthanhtri** [comment] 2019-11-04 05:24
@qiutianme  I build PQ index with your command : 
curl -XPOST -H "content-type:application/json" -d '{
  "engine": {"name": "gamma", "metric_type": method,"max_size":32000000, "index_size": 100000}

}' http://router_ip:router_port/db_name/space_name/_forcemerge 

It's return result   : {"_shards":{"total":2,"successful":1,"failed":1}}  Because one partition can't load by issues question 1 

But  I test search , it's still quite slow (~800 - 1000ms)

**Comment by ansjsun** [comment] 2019-11-04 05:26
@phamthanhtri The indexing process is asynchronous and takes a long time. You can look at the background log or cpu

**Comment by qiutianme** [comment] 2019-11-04 06:44
"On 2 partition server ,server A appear file dump.done , another server B appear file dumping.done " we think your description in question 1 is a normal scene, because your two hosts are not the same hardware capabilities. Why you reload partition server B ? Is it core dump. If partition server B is core dump, Please paste the core dump information.

**Comment by phamthanhtri** [comment] 2019-11-04 07:32
About question 1 .
 - In folder on server B data vearch : /GO_PATH/data_vearch/data/data/29/2019-10-27-23:19:50/ . It have file **dumping**  and when I start service , it cannot be found **dump.done** . But content in file dumping have similar with dump.done
- So I change name file dumping into dump.done and start service. It start successfully but when I run command http://router_ip:router_port/db_name/space_name/_forcemerge . It have error and system kill service.

Log when service is killed: 
   I1104 14:26:48.421061   53617 gamma.go:218] [INFO] index:[29] status is 0
SIGILL: illegal instruction
PC=0x7f2fefd2603b m=23 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x7f2fefd2603b
stack: frame={sp:0x7f1e01f6b480, fp:0x0} stack=[0x7f1e0176d1e8,0x7f1e01f6cde8)

goroutine 167 [syscall]:
runtime.cgocall(0x11fc950, 0xc0004aff40, 0xc0004aff08)
        /usr/lib/golang/src/runtime/cgocall.go:128 +0x5b fp=0xc0004aff10 sp=0xc0004afed8 pc=0x40678b
github.com/vearch/vearch/ps/engine/gammacb._Cfunc_BuildIndex(0x7f2fc00053b0, 0x7f2f00000000)
        _cgo_gotypes.go:245 +0x49 fp=0xc0004aff40 sp=0xc0004aff10 pc=0x11c6b39
github.com/vearch/vearch/ps/engine/gammacb.(*gammaEngine).BuildIndex.func1.1(0x7f2fc00053b0, 0xc00024b3c8)
       /home/GO_PATH/src/github.com/vearch/vearch/ps/engine/gammacb/gamma.go:204 +0x56 fp=0xc0004aff78 sp=0xc0004aff40 pc=0x11d4e66
github.com/vearch/vearch/ps/engine/gammacb.(*gammaEngine).BuildIndex.func1(0x7f2fc00053b0, 0xc00024b380)
       /home/GO_PATH/src/github.com/vearch/vearch/ps/engine/gammacb/gamma.go:204 +0x2f fp=0xc0004affd0 sp=0xc0004aff78 pc=0x11d4eaf
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004affd8 sp=0xc0004affd0 pc=0x462b91
created by github.com/vearch/vearch/ps/engine/gammacb.(*gammaEngine).BuildIndex
       /home/GO_PATH/src/github.com/vearch/vearch/ps/engine/gammacb/gamma.go:203 +0x11b

**Comment by phamthanhtri** [comment] 2019-11-04 10:26
About question 2 :

After I run command: http://router_ip:router_port/db_name/space_name/_forcemerge  . Partition server A excute faster (~30ms) . How to approximate value suitable for **index_size** with my amount of data (30 million items) ?

**Comment by qiutianme** [comment] 2019-11-04 10:56
@phamthanhtri Two points:
1. the "dumping" file is existed, indicating that the service is dumping data. you can't just rename "dumping" file to "dump.done"
2. "SIGILL: illegal instruction", this error message indicates that the CPU on the machine which you deployed vearch does not support avx2 instruction, but your libfaiss.so is compiled with avx2. reference: https://github.com/facebookresearch/faiss/issues/885 

So we suggest you to recompile libfaiss.so on the machine(doesn't support avx2) which you want to deploy vearch, then redeploy vearch, and recreate the space, and reinsert the data. Remember to set the "index_size" parameter when you create the table

**Comment by qiutianme** [comment] 2019-11-04 11:09
# **index_size**

> About question 2 :
> 
> After I run command: http://router_ip:router_port/db_name/space_name/_forcemerge . Partition server A excute faster (~30ms) . How to approximate value suitable for **index_size** with my amount of data (30 million items) ?

100000 is enough

**Comment by phamthanhtri** [comment] 2019-11-04 11:59
Thank  you so much  for  your team 

- Is there any way of calculating the value index_size ? Is it dependency about amount of data ?  If not , Will l set index_size 100000 in all case ?  

-  I will reindex and inform result for you as soon as possible

**Comment by qiutianme** [comment] 2019-11-07 03:05
> Thank you so much for your team
> 
> * Is there any way of calculating the value index_size ? Is it dependency about amount of data ?  If not , Will l set index_size 100000 in all case ?
> * I will reindex and inform result for you as soon as possible

@phamthanhtri  The index_size parameter indicates that the vearch will start indexing when the number of inserted documents reaches the value of index_size. The index_size must be >= 8192 and  <= max_size.  index_size=100000 is enough for the most cases in our practices.

**Comment by phamthanhtri** [comment] 2019-11-07 04:29
Thanks @qiutianme 

I have one more question. When I create space on 2 partition servers  . Each server has 100GB RAM. With my resources I can't set max_size greater than 50 million items .When I set 60 million , system show log error: 

ERROR 2019-11-06 11:17:00,626 memory_raw_vector.cc:34 vector memory alloc err , max_doc_size_ [60000000], dimension_ [512]


Why system distribute into 2 partition servers , but each server must initial 60 million items on gamma ?

**Comment by qiutianme** [comment] 2019-11-08 07:22
> Thanks @qiutianme
> 
> I have one more question. When I create space on 2 partition servers . Each server has 100GB RAM. With my resources I can't set max_size greater than 50 million items .When I set 60 million , system show log error:
> 
> ERROR 2019-11-06 11:17:00,626 memory_raw_vector.cc:34 vector memory alloc err , max_doc_size_ [60000000], dimension_ [512]
> 
> Why system distribute into 2 partition servers , but each server must initial 60 million items on gamma ?

@phamthanhtri  The "max_size" is for partition, not for table. 60 millions items need 120GB(60M * 512 * 4) RAM which is greater than 100GB RAM on your server. So the "max_size" should be < 50 millions on your server

**Comment by phamthanhtri** [comment] 2019-11-08 08:31
Thanks @qiutianme

I am testing v0.2. It has rocksdb . What's new in this version ?

**Comment by qiutianme** [comment] 2019-11-12 01:52
> Thanks @qiutianme
> 
> I am testing v0.2. It has rocksdb . What's new in this version ?

@phamthanhtri  In v0.2, it adds mmap and rocksdb two types to store raw vector, and it has some optimizations, we will update the api documents later. This discussion is beyond the issue, we will close this issue. If you still has other question, please create another issue.

**Closed** 2019-11-12 02:13 UTC
